40.API Read by ID Obat
aldhisttd/5sore_apotek_be pull request #10
Opened 2023-12-10 14:11 UTC by Fahrilnurdian

![image](https://github.com/aldhisttd/5sore_apotek_be/assets/129470765/d2898866-2759-4f34-9e15-b0d0128c77a1)
@aldhi88

2023-12-18 00:36 UTC, aldhi88 requested changes

2023-12-18 00:36 UTC, aldhi88 commented on read_one_obat.php
> +    while ($row = mysqli_fetch_assoc($result)){
@Fahrilnurdian ngapai di loop

2023-12-19 12:13 UTC, Fahrilnurdian commented
![image](https://github.com/aldhisttd/2023_5sore_apotek_be/assets/129470765/b0290e44-4fe3-4797-a560-0447856512da)

2023-12-20 10:47 UTC, aldhi88 approved these changes

2023-12-20 10:47 UTC, merged