34. read supplier be
aldhisttd/5sore_apotek_be pull request #12
Opened 2023-12-11 03:40 UTC by GebyRezeki

![image](https://github.com/aldhisttd/5sore_apotek_be/assets/130050241/6e241ea7-3eb5-47bb-b9aa-74b71fb0e3aa)

2023-12-18 00:28 UTC, aldhi88 requested changes

2023-12-18 00:28 UTC, aldhi88 commented on read_supplier.php
> +if ($rows == 0) {
@GebyRezeki kenapa kalau datanya kosong, hasil response nya jadi error. Harusnya klo datanya kosong ya tetap kembalikan 200, cuma isi datanya kosong, 400 kalau ada error

2023-12-18 12:32 UTC, aldhi88 requested changes

2023-12-18 12:32 UTC, aldhi88 commented on read_supplier.php
> +    while ($row = mysqli_fetch_assoc($result)) {
@GebyRezeki untuk apa ini?

2023-12-18 13:46 UTC, GebyRezeki commented on read_supplier.php
>      while ($row = mysqli_fetch_assoc($result)) {
while untuk looping data pak @aldhi88

2023-12-18 13:49 UTC, aldhi88 requested changes

2023-12-18 13:49 UTC, aldhi88 commented on read_supplier.php
>      while ($row = mysqli_fetch_assoc($result)) {
gak perlu @GebyRezeki

2023-12-18 14:58 UTC, GebyRezeki commented
udh diganti pak @aldhi88 
![image](https://github.com/aldhisttd/2023_5sore_apotek_be/assets/130050241/0a363850-c948-4673-b5ff-349691753c2e)

2023-12-19 00:48 UTC, aldhi88 requested changes
@GebyRezeki sama aja seperti sebelumnya, pahami revisi nya

2023-12-19 01:05 UTC, GebyRezeki commented
jadi gk pakai looping pak @aldhi88 ?

2023-12-20 10:57 UTC, aldhi88 requested changes

2023-12-20 10:57 UTC, aldhi88 commented on read_supplier.php
> +    $row[] = mysqli_fetch_assoc($result);
kenapa $row nya jadi array, var biasa aja. @GebyRezeki

2023-12-20 14:45 UTC, GebyRezeki commented on read_supplier.php
> +}
kalau masi salah tolong instruksinya yg jelas pak @aldhi88

2023-12-20 14:45 UTC, GebyRezeki commented on read_supplier.php
> +    $row = mysqli_fetch_assoc($result);
udah var biasa pak @aldhi88. ini read all emang gk perlu **WHILE** supaya dapat semua datanya pak?

2023-12-21 05:31 UTC, aldhi88 approved these changes

2023-12-21 05:31 UTC, merged