41. update obat bugfix
aldhisttd/5sore_apotek_be pull request #21
Opened 2023-12-28 03:22 UTC by GebyRezeki

![image](https://github.com/aldhisttd/2023_5sore_apotek_be/assets/130050241/cbd51b70-5b5f-416f-8fb1-9cfff2876470)

2023-12-28 03:36 UTC, aldhi88 requested changes
@GebyRezeki , di DB alamat gambar memang ada `upload/` nya. Unlink kamu yg salah

2023-12-28 03:41 UTC, GebyRezeki commented
> @GebyRezeki , di DB alamat gambar memang ada `upload/` nya. Unlink kamu yg salah

sesuai gambar yg saya kirim pak, sudah tidak ada **upload/** di DBnya

2023-12-29 06:21 UTC, aldhi88 requested changes
@GebyRezeki , bukan gini mksnya, di DB itu memang harus ada `upload/` nya, jadi unlink kamu itu salah. pas buat nama gambar baru juga tambahkan `upload/` nya....utk apa kamu hapus di db nya

2023-12-29 06:21 UTC, aldhi88 commented on update_obat.php
> +        mysqli_query($koneksi, "UPDATE obat SET gambar = '$namaGambarBaru' WHERE kode = '$kode'");
nama gambarnya `upload/nama_gambar` @GebyRezeki

2023-12-29 16:57 UTC, GebyRezeki commented on update_obat.php
> +        mysqli_query($koneksi, "UPDATE obat SET gambar = 'upload/$namaGambarBaru' WHERE kode = '$kode'");
@aldhi88 sudah seperti awal

2023-12-29 16:57 UTC, GebyRezeki commented on update_obat.php
> +        unlink($gambar);
@aldhi88

2023-12-30 00:55 UTC, aldhi88 approved these changes

2023-12-30 00:55 UTC, merged