39 API Read All Obat
aldhisttd/5sore_apotek_be pull request #22
Opened 2023-12-30 10:05 UTC by ayukumaladewi

![image](https://github.com/aldhisttd/2023_5sore_apotek_be/assets/130049759/abfaf477-d983-4ec8-8cbc-06f687d4abc7)

2023-12-31 06:02 UTC, aldhi88 requested changes

2023-12-31 06:02 UTC, aldhi88 commented on read_obat.php
@ayukumaladewi mana screenshot postman nya

2024-01-01 12:38 UTC, ayukumaladewi commented on read_obat.php
@aldhi88 diatas ss-an nya pak

2024-01-02 07:11 UTC, aldhi88 approved these changes

2024-01-02 07:11 UTC, merged