38.API create obat
aldhisttd/5sore_apotek_be pull request #4
Opened 2023-12-10 11:48 UTC by ayukumaladewi

![image](https://github.com/aldhisttd/5sore_apotek_be/assets/130049759/9f40a66d-54b8-421b-ab04-113ec4aef7e3)
@aldhi88

2023-12-10 11:54 UTC, aldhi88 requested changes

2023-12-10 11:54 UTC, aldhi88 commented on input_obat.php
@ayukumaladewi handle file upload nya mana?, tolong screenshoot nya lampirkan juga payloadnya

2023-12-11 10:37 UTC, ayukumaladewi commented on input_obat.php
![image](https://github.com/aldhisttd/5sore_apotek_be/assets/130049759/72cc34eb-1701-4e40-aea6-31faa5ae97dd)
![image](https://github.com/aldhisttd/5sore_apotek_be/assets/130049759/682043de-5214-449d-9d40-efcb2a2f9649)
sudah pak @aldhi88

2023-12-18 00:22 UTC, aldhi88 requested changes

2023-12-18 00:22 UTC, aldhi88 commented on input_obat.php
> +    $gambar = basename($_FILES["gambar"]["name"]);
@ayukumaladewi , kalau seperti ini nama file gambar adalah nama file yg di upload, kalau yg di upload kebetulan nama file nya sama maka gambar yg udah di upload sebelumnya akan di replace, solusi nya adalah setiap gambar yg di upload harus kita ganti nama nya menjadi string uniq,

pake fungsi ini : 
`$nama_gambar = md5(date('dmy h:i:s'));`

fungsi diatas akan generate uniq string, tinggal tambahkan extension dari file nya, jadi kamu harus dapat dulu extension dari file nya, nnti satukan nama_gambar dengan extension nya.

2023-12-19 11:35 UTC, ayukumaladewi commented on image.php
> +move_uploaded_file($_FILES["gambar"]["tmp_name"], $target_file);
@aldhi88

2023-12-20 10:53 UTC, aldhi88 requested changes

2023-12-20 10:53 UTC, aldhi88 commented on image.php
ini file apa @ayukumaladewi , saya gak ada buat file ini

2023-12-20 10:53 UTC, aldhi88 commented on upload/062447bd7db637cd94a661f402e3a805.jpg
ini file gambarnya sebelum PR dihapus dulu biar gak masuk @ayukumaladewi

2023-12-21 05:44 UTC, aldhi88 approved these changes

2023-12-21 05:44 UTC, merged