36. Update Supplier BE
aldhisttd/5sore_apotek_be pull request #5
Opened 2023-12-10 12:01 UTC by Arini261203

![image](https://github.com/aldhisttd/5sore_apotek_be/assets/131981558/a586f26b-822e-4696-ab2f-d2ed2ad3fbb2)
![image](https://github.com/aldhisttd/5sore_apotek_be/assets/131981558/586adb27-0b18-4c99-b45d-c4ecef86bf54)

2023-12-10 12:07 UTC, aldhi88 requested changes

2023-12-10 12:07 UTC, aldhi88 commented on update_supplier.php
> +mysqli_query($koneksi, "UPDATE supplier SET kode = '$kode', nama = '$nama', alamat = '$alamat', hp = '$hp' WHERE kode = '$kode'");
@Arini261203 buat handle query nya klo gagal, kembalikan response gagal sesuai API Spek
line 17 masukkan ke dalam variable,

2023-12-10 12:35 UTC, Arini261203 commented on update_supplier.php
> +} else {
@aldhi88

2023-12-18 00:45 UTC, aldhi88 requested changes

2023-12-18 00:45 UTC, aldhi88 commented on update_supplier.php
> +    mysqli_query($koneksi, "UPDATE supplier SET kode = '$kode', nama = '$nama', alamat = '$alamat', hp = '$hp' WHERE kode = '$kode'");
@Arini261203 kode nya jgn di update, harusnya query ini gagal klo kodenya di ubah sama client

2023-12-20 10:07 UTC, Arini261203 commented on update_supplier.php
> +    mysqli_query($koneksi, "UPDATE supplier SET nama = '$nama', alamat = '$alamat', hp = '$hp' WHERE kode = '$kode'");
hapus kode=$kode @aldhi88

2023-12-20 10:43 UTC, aldhi88 approved these changes

2023-12-20 10:43 UTC, merged