30. Read One Kategori BE
aldhisttd/5sore_apotek_be pull request #6
Opened 2023-12-10 13:13 UTC by Arini261203

![image](https://github.com/aldhisttd/5sore_apotek_be/assets/131981558/81fd83ee-7e23-4dd4-8358-cc1ccc3908d1)

2023-12-18 00:37 UTC, aldhi88 requested changes

2023-12-18 00:37 UTC, aldhi88 commented on read_one_kategori.php
> +    while ($row = mysqli_fetch_assoc($result)){
@Arini261203 ngapai di looping

2023-12-20 10:00 UTC, Arini261203 commented on read_one_kategori.php
> +
sudah tidak ada whilenya pak @aldhi88

2023-12-20 10:44 UTC, aldhi88 approved these changes

2023-12-20 10:44 UTC, merged