31.API Update Kategori
aldhisttd/5sore_apotek_be pull request #9
Opened 2023-12-10 13:56 UTC by Fahrilnurdian

![image](https://github.com/aldhisttd/5sore_apotek_be/assets/129470765/b452774f-0ba6-4a81-954b-e84e154d98de)
@aldhi88

2023-12-18 00:35 UTC, aldhi88 requested changes
@Fahrilnurdian revisi :
- rapikan code nya
- sertakan hasil postman dan perubahan di phpmyadmin
- perbaiki line 23

2023-12-18 00:35 UTC, aldhi88 commented on update_kategori.php
> +mysqli_query($koneksi, "UPDATE kategori SET kode = '$kode', nama = '$nama' WHERE kode = '$kode'");
@Fahrilnurdian ini harusnya error, datanya tidak ter update, harusnya yg boleh di edit hanya nama

2023-12-19 11:58 UTC, Fahrilnurdian commented
![image](https://github.com/aldhisttd/2023_5sore_apotek_be/assets/129470765/703db54b-4b99-477a-ad18-f17860243483)
![image](https://github.com/aldhisttd/2023_5sore_apotek_be/assets/129470765/2eadf082-eac5-4f5f-aa4d-225230d22b0e)
![image](https://github.com/aldhisttd/2023_5sore_apotek_be/assets/129470765/cb564433-205b-4a7a-a571-b4fc49c0b081)

2023-12-20 10:49 UTC, aldhi88 approved these changes

2023-12-20 10:49 UTC, merged